src search "context:global select:file visibility:public count:all lang:Python content:'from spacy' AND load\(" > result_file_fromimport_spacy_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from transformers' AND pipeline\(" > result_file_fromimport_transformers_pipeline.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from allennlp' AND from_path\(" > result_file_fromimport_allennlp_from_path.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from asteroid' AND from_pretrained\(" > result_file_fromimport_asteroid_from_pretrained.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from espnet2' AND from_pretrained\(" > result_file_fromimport_espnet2_from_pretrained.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from nemo' AND from_pretrained\(" > result_file_fromimport_nemo_from_pretrained.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from paddlenlp' AND from_pretrained\(" > result_file_fromimport_paddlenlp_from_pretrained.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from pyannote' AND from_pretrained\(" > result_file_fromimport_pyannote_from_pretrained.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from sentence_transformers' AND SentenceTransformer\(" > result_file_fromimport_sentence_transformers_SentenceTransformer.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from speechbrain' AND from_hparams\(" > result_file_fromimport_speechbrain_from_hparams.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from tensorflow_tts' AND from_pretrained\(" > result_file_fromimport_tensorflow_tts_from_pretrained.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from timm' AND create_model\(" > result_file_fromimport_timm_create_model.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from stanza' AND download\(" > result_file_fromimport_stanza_download.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from stanza' AND Pipeline\(" > result_file_fromimport_stanza_Pipeline.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from flair' AND load\(" > result_file_fromimport_flair_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from fairseq' AND load_model_ensemble_and_task_from_hf_hub\(" > result_file_fromimport_fairseq_load_model_ensemble_and_task_from_hf_hub.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from huggingface_hub' AND from_pretrained_keras\(" > result_file_fromimport_huggingface_hub_from_pretrained_keras.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from huggingface_hub' AND load\(" > result_file_fromimport_huggingface_hub_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from huggingface_hub' AND from_pretrained_fastai\(" > result_file_fromimport_huggingface_hub_from_pretrained_fastai.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from huggingface_hub' AND hf_hub_download\(" > result_file_fromimport_huggingface_hub_hf_hub_download.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from bertopic' AND load\(" > result_file_fromimport_bertopic_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from diffusers' AND from_pretrained\(" > result_file_fromimport_diffusers_from_pretrained.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from open_clip' AND create_model_and_transforms\(" > result_file_fromimport_open_clip_create_model_and_transforms.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from open_clip' AND get_tokenizer\(" > result_file_fromimport_open_clip_get_tokenizer.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from peft' AND from_pretrained\(" > result_file_fromimport_peft_from_pretrained.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from span_marker' AND from_pretrained\(" > result_file_fromimport_span_marker_from_pretrained.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from huggingface_sb3' AND load_from_hub\(" > result_file_fromimport_huggingface_sb3_load_from_hub.csv
src search "context:global select:file visibility:public count:all lang:Python content:'from pythae' AND load_from_hf_hub\(" > result_file_fromimport_pythae_load_from_hf_hub.csv

