src search "context:global select:file visibility:public count:all lang:Python content:'import en_textcat_emotion_umberto' AND load\(" > file_spacy_2_en_textcat_emotion_umberto_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_textcat_emotion_xlm' AND load\(" > file_spacy_2_en_textcat_emotion_xlm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import it_textcat_emotion_umberto' AND load\(" > file_spacy_2_it_textcat_emotion_umberto_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_roberta_base_leetspeak_ner' AND load\(" > file_spacy_2_en_roberta_base_leetspeak_ner_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import es_roberta_base_bne_leetspeak_ner' AND load\(" > file_spacy_2_es_roberta_base_bne_leetspeak_ner_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import grc_ud_perseus_dioberto' AND load\(" > file_spacy_2_grc_ud_perseus_dioberto_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import grc_ud_perseus_lg' AND load\(" > file_spacy_2_grc_ud_perseus_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import grc_ud_perseus_lge' AND load\(" > file_spacy_2_grc_ud_perseus_lge_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import grc_ud_perseus_trf' AND load\(" > file_spacy_2_grc_ud_perseus_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import grc_ud_proiel_dioberto' AND load\(" > file_spacy_2_grc_ud_proiel_dioberto_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import grc_ud_proiel_lg' AND load\(" > file_spacy_2_grc_ud_proiel_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import swedish-spacy-pipeline' AND load\(" > file_spacy_2_swedish-spacy-pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pipeline' AND load\(" > file_spacy_2_en_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_scibert_ScienceIE' AND load\(" > file_spacy_2_en_scibert_ScienceIE_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pipeline' AND load\(" > file_spacy_2_en_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import hi_ud_hi_ewt' AND load\(" > file_spacy_2_hi_ud_hi_ewt_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import da_dacy_large_trf' AND load\(" > file_spacy_2_da_dacy_large_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import da_dacy_medium_trf' AND load\(" > file_spacy_2_da_dacy_medium_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import da_dacy_small_trf' AND load\(" > file_spacy_2_da_dacy_small_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_statistics' AND load\(" > file_spacy_2_en_statistics_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_stylecheck' AND load\(" > file_spacy_2_en_stylecheck_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import de_MRP_NER' AND load\(" > file_spacy_2_de_MRP_NER_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import de_RTA_NER' AND load\(" > file_spacy_2_de_RTA_NER_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import xx_cat_pateexx_md' AND load\(" > file_spacy_2_xx_cat_pateexx_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pipeline' AND load\(" > file_spacy_2_en_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_acnl_electra_pipeline' AND load\(" > file_spacy_2_en_acnl_electra_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_acnl_roberta_pipeline' AND load\(" > file_spacy_2_en_acnl_roberta_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import hr_bertic_pipeline' AND load\(" > file_spacy_2_hr_bertic_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import hr_hroberta_pipeline' AND load\(" > file_spacy_2_hr_hroberta_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import is_core_web_trf' AND load\(" > file_spacy_2_is_core_web_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import is_ner_mim_sm' AND load\(" > file_spacy_2_is_ner_mim_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import is_ner_mim_trf' AND load\(" > file_spacy_2_is_ner_mim_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import is_ud_is_pud' AND load\(" > file_spacy_2_is_ud_is_pud_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import af_udv25_afrikaansafribooms_trf' AND load\(" > file_spacy_2_af_udv25_afrikaansafribooms_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import da_udv25_danishddt_trf' AND load\(" > file_spacy_2_da_udv25_danishddt_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import de_udv25_germanhdt_trf' AND load\(" > file_spacy_2_de_udv25_germanhdt_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_healthsea' AND load\(" > file_spacy_2_en_healthsea_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_textcat_goemotions' AND load\(" > file_spacy_2_en_textcat_goemotions_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_udv25_englishewt_trf' AND load\(" > file_spacy_2_en_udv25_englishewt_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import es_udv25_spanishancora_trf' AND load\(" > file_spacy_2_es_udv25_spanishancora_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import fi_udv25_finnishtdt_trf' AND load\(" > file_spacy_2_fi_udv25_finnishtdt_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import fr_udv25_frenchsequoia_trf' AND load\(" > file_spacy_2_fr_udv25_frenchsequoia_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ga_udv25_irishidt_trf' AND load\(" > file_spacy_2_ga_udv25_irishidt_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import hr_udv25_croatianset_trf' AND load\(" > file_spacy_2_hr_udv25_croatianset_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import id_udv25_indonesiangsd_trf' AND load\(" > file_spacy_2_id_udv25_indonesiangsd_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ko_udv25_koreangsd_trf' AND load\(" > file_spacy_2_ko_udv25_koreangsd_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ko_udv25_koreankaist_trf' AND load\(" > file_spacy_2_ko_udv25_koreankaist_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import lt_udv25_lithuanianalksnis_trf' AND load\(" > file_spacy_2_lt_udv25_lithuanianalksnis_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import lv_udv25_latvianlvtb_trf' AND load\(" > file_spacy_2_lv_udv25_latvianlvtb_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import nb_udv25_norwegianbokmaal_trf' AND load\(" > file_spacy_2_nb_udv25_norwegianbokmaal_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import nb_udv25_norwegiannynorsk_trf' AND load\(" > file_spacy_2_nb_udv25_norwegiannynorsk_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import nl_udv25_dutchalpino_trf' AND load\(" > file_spacy_2_nl_udv25_dutchalpino_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import nl_udv25_dutchlassysmall_trf' AND load\(" > file_spacy_2_nl_udv25_dutchlassysmall_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import pl_udv25_polishlfg_trf' AND load\(" > file_spacy_2_pl_udv25_polishlfg_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import pt_udv25_portuguesebosque_trf' AND load\(" > file_spacy_2_pt_udv25_portuguesebosque_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ro_udv25_romaniannonstandard_trf' AND load\(" > file_spacy_2_ro_udv25_romaniannonstandard_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ro_udv25_romanianrrt_trf' AND load\(" > file_spacy_2_ro_udv25_romanianrrt_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ru_udv25_russiangsd_trf' AND load\(" > file_spacy_2_ru_udv25_russiangsd_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import sk_udv25_slovaksnk_trf' AND load\(" > file_spacy_2_sk_udv25_slovaksnk_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import sr_udv25_serbianset_trf' AND load\(" > file_spacy_2_sr_udv25_serbianset_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import sv_udv25_swedishtalbanken_trf' AND load\(" > file_spacy_2_sv_udv25_swedishtalbanken_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import vi_udv25_vietnamesevtb_trf' AND load\(" > file_spacy_2_vi_udv25_vietnamesevtb_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import xx_udv25_oldfrenchsrcmf_trf' AND load\(" > file_spacy_2_xx_udv25_oldfrenchsrcmf_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ja_gsd_bert_wwm_unidic_lite' AND load\(" > file_spacy_2_ja_gsd_bert_wwm_unidic_lite_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import hu_core_news_lg' AND load\(" > file_spacy_2_hu_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_core_med7_lg' AND load\(" > file_spacy_2_en_core_med7_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_core_med7_trf' AND load\(" > file_spacy_2_en_core_med7_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import da_core_news_sm' AND load\(" > file_spacy_2_da_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import el_core_news_sm' AND load\(" > file_spacy_2_el_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_ner_fashion' AND load\(" > file_spacy_2_en_ner_fashion_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import fashion_brands_patterns' AND load\(" > file_spacy_2_fashion_brands_patterns_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import test123' AND load\(" > file_spacy_2_test123_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import test_meta' AND load\(" > file_spacy_2_test_meta_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pipeline' AND load\(" > file_spacy_2_en_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_model_ner_skills' AND load\(" > file_spacy_2_en_model_ner_skills_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_ner_model' AND load\(" > file_spacy_2_en_ner_model_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_ner_skills' AND load\(" > file_spacy_2_en_ner_skills_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import nb_nocy_trf' AND load\(" > file_spacy_2_nb_nocy_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ca_core_news_lg' AND load\(" > file_spacy_2_ca_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ca_core_news_md' AND load\(" > file_spacy_2_ca_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ca_core_news_sm' AND load\(" > file_spacy_2_ca_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ca_core_news_trf' AND load\(" > file_spacy_2_ca_core_news_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import da_core_news_lg' AND load\(" > file_spacy_2_da_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import da_core_news_md' AND load\(" > file_spacy_2_da_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import da_core_news_sm' AND load\(" > file_spacy_2_da_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import da_core_news_trf' AND load\(" > file_spacy_2_da_core_news_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import de_core_news_lg' AND load\(" > file_spacy_2_de_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import de_core_news_md' AND load\(" > file_spacy_2_de_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import de_core_news_sm' AND load\(" > file_spacy_2_de_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import de_dep_news_trf' AND load\(" > file_spacy_2_de_dep_news_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import el_core_news_lg' AND load\(" > file_spacy_2_el_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import el_core_news_md' AND load\(" > file_spacy_2_el_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import el_core_news_sm' AND load\(" > file_spacy_2_el_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_core_web_lg' AND load\(" > file_spacy_2_en_core_web_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_core_web_md' AND load\(" > file_spacy_2_en_core_web_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_core_web_sm' AND load\(" > file_spacy_2_en_core_web_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_core_web_trf' AND load\(" > file_spacy_2_en_core_web_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import es_core_news_lg' AND load\(" > file_spacy_2_es_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import es_core_news_md' AND load\(" > file_spacy_2_es_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import es_core_news_sm' AND load\(" > file_spacy_2_es_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import es_dep_news_trf' AND load\(" > file_spacy_2_es_dep_news_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import fr_core_news_lg' AND load\(" > file_spacy_2_fr_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import fr_core_news_md' AND load\(" > file_spacy_2_fr_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import fr_core_news_sm' AND load\(" > file_spacy_2_fr_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import fr_dep_news_trf' AND load\(" > file_spacy_2_fr_dep_news_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import it_core_news_lg' AND load\(" > file_spacy_2_it_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import it_core_news_md' AND load\(" > file_spacy_2_it_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import it_core_news_sm' AND load\(" > file_spacy_2_it_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ja_core_news_lg' AND load\(" > file_spacy_2_ja_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ja_core_news_md' AND load\(" > file_spacy_2_ja_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ja_core_news_sm' AND load\(" > file_spacy_2_ja_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ja_core_news_trf' AND load\(" > file_spacy_2_ja_core_news_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import lt_core_news_lg' AND load\(" > file_spacy_2_lt_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import lt_core_news_md' AND load\(" > file_spacy_2_lt_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import lt_core_news_sm' AND load\(" > file_spacy_2_lt_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import mk_core_news_lg' AND load\(" > file_spacy_2_mk_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import mk_core_news_md' AND load\(" > file_spacy_2_mk_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import mk_core_news_sm' AND load\(" > file_spacy_2_mk_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import nb_core_news_lg' AND load\(" > file_spacy_2_nb_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import nb_core_news_md' AND load\(" > file_spacy_2_nb_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import nb_core_news_sm' AND load\(" > file_spacy_2_nb_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import nl_core_news_lg' AND load\(" > file_spacy_2_nl_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import nl_core_news_md' AND load\(" > file_spacy_2_nl_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import nl_core_news_sm' AND load\(" > file_spacy_2_nl_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import pl_core_news_lg' AND load\(" > file_spacy_2_pl_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import pl_core_news_md' AND load\(" > file_spacy_2_pl_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import pl_core_news_sm' AND load\(" > file_spacy_2_pl_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import pt_core_news_lg' AND load\(" > file_spacy_2_pt_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import pt_core_news_md' AND load\(" > file_spacy_2_pt_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import pt_core_news_sm' AND load\(" > file_spacy_2_pt_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ro_core_news_lg' AND load\(" > file_spacy_2_ro_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ro_core_news_md' AND load\(" > file_spacy_2_ro_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ro_core_news_sm' AND load\(" > file_spacy_2_ro_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ru_core_news_lg' AND load\(" > file_spacy_2_ru_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ru_core_news_md' AND load\(" > file_spacy_2_ru_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ru_core_news_sm' AND load\(" > file_spacy_2_ru_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import xx_ent_wiki_sm' AND load\(" > file_spacy_2_xx_ent_wiki_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import xx_sent_ud_sm' AND load\(" > file_spacy_2_xx_sent_ud_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import zh_core_web_lg' AND load\(" > file_spacy_2_zh_core_web_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import zh_core_web_md' AND load\(" > file_spacy_2_zh_core_web_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import zh_core_web_sm' AND load\(" > file_spacy_2_zh_core_web_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import zh_core_web_trf' AND load\(" > file_spacy_2_zh_core_web_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_abbreviation_detection_roberta_lar' AND load\(" > file_spacy_2_en_abbreviation_detection_roberta_lar_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pos_counter' AND load\(" > file_spacy_2_en_pos_counter_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_readability' AND load\(" > file_spacy_2_en_readability_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import fr_ner_ingredients' AND load\(" > file_spacy_2_fr_ner_ingredients_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import fr_pipeline' AND load\(" > file_spacy_2_fr_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_docusco_spacy' AND load\(" > file_spacy_2_en_docusco_spacy_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import it_nerIta_trf' AND load\(" > file_spacy_2_it_nerIta_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import hu_core_news_trf' AND load\(" > file_spacy_2_hu_core_news_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import es_tweets_laboral' AND load\(" > file_spacy_2_es_tweets_laboral_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import uk_core_news_trf' AND load\(" > file_spacy_2_uk_core_news_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pipeline' AND load\(" > file_spacy_2_en_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_BiomedNER_EuropePMC' AND load\(" > file_spacy_2_en_BiomedNER_EuropePMC_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_tenarchexp3' AND load\(" > file_spacy_2_en_tenarchexp3_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_covid19_ner' AND load\(" > file_spacy_2_en_covid19_ner_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import hu_vectors_web_lg' AND load\(" > file_spacy_2_hu_vectors_web_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_tenarch_archetypes' AND load\(" > file_spacy_2_en_tenarch_archetypes_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import sv_core_news_sm' AND load\(" > file_spacy_2_sv_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import sv_core_news_md' AND load\(" > file_spacy_2_sv_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import sv_core_news_lg' AND load\(" > file_spacy_2_sv_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ko_core_news_sm' AND load\(" > file_spacy_2_ko_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ko_core_news_md' AND load\(" > file_spacy_2_ko_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ko_core_news_lg' AND load\(" > file_spacy_2_ko_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import fi_core_news_sm' AND load\(" > file_spacy_2_fi_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import fi_core_news_md' AND load\(" > file_spacy_2_fi_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import fi_core_news_lg' AND load\(" > file_spacy_2_fi_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pipeline' AND load\(" > file_spacy_2_en_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pipeline' AND load\(" > file_spacy_2_en_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pipeline' AND load\(" > file_spacy_2_en_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_sdoh_roberta_cui' AND load\(" > file_spacy_2_en_sdoh_roberta_cui_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_tenarch_aspects' AND load\(" > file_spacy_2_en_tenarch_aspects_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pipeline' AND load\(" > file_spacy_2_en_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import dataset-references' AND load\(" > file_spacy_2_dataset-references_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pubmed_en' AND load\(" > file_spacy_2_en_pubmed_en_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pubmed_rct' AND load\(" > file_spacy_2_en_pubmed_rct_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_error_causes' AND load\(" > file_spacy_2_en_error_causes_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_grammar_checker' AND load\(" > file_spacy_2_en_grammar_checker_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import tr_floret_web_md' AND load\(" > file_spacy_2_tr_floret_web_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import tr_floret_web_lg' AND load\(" > file_spacy_2_tr_floret_web_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_tenarch_seniority' AND load\(" > file_spacy_2_en_tenarch_seniority_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import de_dep_hdt_dist' AND load\(" > file_spacy_2_de_dep_hdt_dist_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pipeline' AND load\(" > file_spacy_2_en_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import de_dep_hdt_sm' AND load\(" > file_spacy_2_de_dep_hdt_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import de_dep_hdt_trf' AND load\(" > file_spacy_2_de_dep_hdt_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import de_dep_hdt_lg' AND load\(" > file_spacy_2_de_dep_hdt_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import de_GERNERMEDpp_GottBERT' AND load\(" > file_spacy_2_de_GERNERMEDpp_GottBERT_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import de_GERNERMEDpp_Slim' AND load\(" > file_spacy_2_de_GERNERMEDpp_Slim_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import de_GERNERMEDpp_GermanBERT' AND load\(" > file_spacy_2_de_GERNERMEDpp_GermanBERT_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ca_core_news_sm' AND load\(" > file_spacy_2_ca_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_core_web_sm' AND load\(" > file_spacy_2_en_core_web_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import hr_core_news_sm' AND load\(" > file_spacy_2_hr_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import hr_core_news_md' AND load\(" > file_spacy_2_hr_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import hr_core_news_lg' AND load\(" > file_spacy_2_hr_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import LandmarkNER' AND load\(" > file_spacy_2_LandmarkNER_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import fr_ner4archives_default_test' AND load\(" > file_spacy_2_fr_ner4archives_default_test_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import hu_vectors_web_md' AND load\(" > file_spacy_2_hu_vectors_web_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import fr_ner4archives_camembert_base' AND load\(" > file_spacy_2_fr_ner4archives_camembert_base_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_reciparse_model' AND load\(" > file_spacy_2_en_reciparse_model_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_med12_trf' AND load\(" > file_spacy_2_en_med12_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pipeline' AND load\(" > file_spacy_2_en_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pipeline' AND load\(" > file_spacy_2_en_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_med12_trf_weakly_supervised' AND load\(" > file_spacy_2_en_med12_trf_weakly_supervised_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_stonk_pipeline' AND load\(" > file_spacy_2_en_stonk_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_MARTIME_NER' AND load\(" > file_spacy_2_en_MARTIME_NER_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pipeline' AND load\(" > file_spacy_2_en_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import grc_ud_proiel_sm' AND load\(" > file_spacy_2_grc_ud_proiel_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_legal_ner_trf' AND load\(" > file_spacy_2_en_legal_ner_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_legal_ner_sm' AND load\(" > file_spacy_2_en_legal_ner_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_core_sci_md' AND load\(" > file_spacy_2_en_core_sci_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pipeline' AND load\(" > file_spacy_2_en_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import es_pipeline' AND load\(" > file_spacy_2_es_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_ner_vc_lg' AND load\(" > file_spacy_2_en_ner_vc_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import fr_ner4archives_v3_default' AND load\(" > file_spacy_2_fr_ner4archives_v3_default_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import grc_ud_proiel_md' AND load\(" > file_spacy_2_grc_ud_proiel_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import hu_core_news_md' AND load\(" > file_spacy_2_hu_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_spacy_wnut_roberta_base_ner' AND load\(" > file_spacy_2_en_spacy_wnut_roberta_base_ner_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_spacy_conll2003_roberta_base_ner' AND load\(" > file_spacy_2_en_spacy_conll2003_roberta_base_ner_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_spacy_ontonotes_roberta_base_ner' AND load\(" > file_spacy_2_en_spacy_ontonotes_roberta_base_ner_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_spacy_conll2003_distilroberta_base_ner' AND load\(" > file_spacy_2_en_spacy_conll2003_distilroberta_base_ner_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_spacy_wnut_distilroberta_base_ner' AND load\(" > file_spacy_2_en_spacy_wnut_distilroberta_base_ner_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_spacy_fewnerd_roberta_base_ner' AND load\(" > file_spacy_2_en_spacy_fewnerd_roberta_base_ner_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_spacy_fewnerd_distilroberta_base_ner' AND load\(" > file_spacy_2_en_spacy_fewnerd_distilroberta_base_ner_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_spacy_ontonotes_distilroberta_base_ner' AND load\(" > file_spacy_2_en_spacy_ontonotes_distilroberta_base_ner_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_spacy_pii_fast' AND load\(" > file_spacy_2_en_spacy_pii_fast_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_spacy_pii_lg' AND load\(" > file_spacy_2_en_spacy_pii_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_spacy_pii_distilbert' AND load\(" > file_spacy_2_en_spacy_pii_distilbert_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_spacy_conll2003_xlm_roberta_base_ner' AND load\(" > file_spacy_2_en_spacy_conll2003_xlm_roberta_base_ner_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_spacy_wnut_xlm_roberta_base_ner' AND load\(" > file_spacy_2_en_spacy_wnut_xlm_roberta_base_ner_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import fr_ner4archives_v3_with_vectors' AND load\(" > file_spacy_2_fr_ner4archives_v3_with_vectors_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import fr_ner4archives_V3_camembert_base' AND load\(" > file_spacy_2_fr_ner4archives_V3_camembert_base_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import uk_ner_web_trf_base' AND load\(" > file_spacy_2_uk_ner_web_trf_base_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ca_bsc_demo_trf' AND load\(" > file_spacy_2_ca_bsc_demo_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pipeline' AND load\(" > file_spacy_2_en_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import uk_ner_web_trf_large' AND load\(" > file_spacy_2_uk_ner_web_trf_large_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import tr_core_news_trf' AND load\(" > file_spacy_2_tr_core_news_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_engagement_RoBERTa_combined' AND load\(" > file_spacy_2_en_engagement_RoBERTa_combined_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import tr_vectors_web_md' AND load\(" > file_spacy_2_tr_vectors_web_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import tr_vectors_web_lg' AND load\(" > file_spacy_2_tr_vectors_web_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import tr_core_news_md' AND load\(" > file_spacy_2_tr_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import tr_core_news_lg' AND load\(" > file_spacy_2_tr_core_news_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pipeline_123' AND load\(" > file_spacy_2_en_pipeline_123_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_core_web_lg' AND load\(" > file_spacy_2_en_core_web_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import grc_ud_proiel_trf' AND load\(" > file_spacy_2_grc_ud_proiel_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import pt_core_news_trf' AND load\(" > file_spacy_2_pt_core_news_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import es_pharmaconer_ner_trf' AND load\(" > file_spacy_2_es_pharmaconer_ner_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import es_cantemist_ner_trf' AND load\(" > file_spacy_2_es_cantemist_ner_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_student_name_detector' AND load\(" > file_spacy_2_en_student_name_detector_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import da_core_news_sm' AND load\(" > file_spacy_2_da_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import es_pharmaconer_ner_trf' AND load\(" > file_spacy_2_es_pharmaconer_ner_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import es_bsc_demo_trf' AND load\(" > file_spacy_2_es_bsc_demo_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_core_spancat_med7_trf' AND load\(" > file_spacy_2_en_core_spancat_med7_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import de_fnhd_nerdh' AND load\(" > file_spacy_2_de_fnhd_nerdh_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_core_spancat_med7_lg' AND load\(" > file_spacy_2_en_core_spancat_med7_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import meddner' AND load\(" > file_spacy_2_meddner_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_triage_subject' AND load\(" > file_spacy_2_en_triage_subject_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_Coff_Ev1' AND load\(" > file_spacy_2_en_Coff_Ev1_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ca_bsc_demo_md' AND load\(" > file_spacy_2_ca_bsc_demo_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import es_bsc_demo_md' AND load\(" > file_spacy_2_es_bsc_demo_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import xx_pipeline' AND load\(" > file_spacy_2_xx_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import xx_LeetSpeakNER_mstsb_mpnet' AND load\(" > file_spacy_2_xx_LeetSpeakNER_mstsb_mpnet_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_engagement_spl_RoBERTa_acad_max1_do02' AND load\(" > file_spacy_2_en_engagement_spl_RoBERTa_acad_max1_do02_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_Coff_Ev2' AND load\(" > file_spacy_2_en_Coff_Ev2_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_food_entity_extractor_v2' AND load\(" > file_spacy_2_en_food_entity_extractor_v2_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_docusco_spacy_fc' AND load\(" > file_spacy_2_en_docusco_spacy_fc_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_docusco_spacy_fc_trf' AND load\(" > file_spacy_2_en_docusco_spacy_fc_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_grantss' AND load\(" > file_spacy_2_en_grantss_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_grant' AND load\(" > file_spacy_2_en_grant_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_ncv' AND load\(" > file_spacy_2_en_ncv_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_engagement_spl_RoBERTa2' AND load\(" > file_spacy_2_en_engagement_spl_RoBERTa2_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_textcat_multilabel_demo' AND load\(" > file_spacy_2_en_textcat_multilabel_demo_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_ner_prompting' AND load\(" > file_spacy_2_en_ner_prompting_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_engagement_spl_RoBERTa_acad' AND load\(" > file_spacy_2_en_engagement_spl_RoBERTa_acad_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_nlp_ner_transformer_pipeline' AND load\(" > file_spacy_2_en_nlp_ner_transformer_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ca_bsc_ud11_trf' AND load\(" > file_spacy_2_ca_bsc_ud11_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ca_anonimization_core_lg' AND load\(" > file_spacy_2_ca_anonimization_core_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import es_spacy_ner_cds' AND load\(" > file_spacy_2_es_spacy_ner_cds_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import ca_bsc_core_trf' AND load\(" > file_spacy_2_ca_bsc_core_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pipeline' AND load\(" > file_spacy_2_en_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import es_spacy_ner_cds_trf' AND load\(" > file_spacy_2_es_spacy_ner_cds_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_nature_of_li_multilabel' AND load\(" > file_spacy_2_en_nature_of_li_multilabel_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import pt_lg_pipeline' AND load\(" > file_spacy_2_pt_lg_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import pt_pipeline' AND load\(" > file_spacy_2_pt_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import grc_homercy_treebanks_sm' AND load\(" > file_spacy_2_grc_homercy_treebanks_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import xx_ner_sport_entities_uncased' AND load\(" > file_spacy_2_xx_ner_sport_entities_uncased_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import es_anonimization_core_lg' AND load\(" > file_spacy_2_es_anonimization_core_lg_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import grc_homercy_treebanks_trf' AND load\(" > file_spacy_2_grc_homercy_treebanks_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_engagement_spl_RoBERTa_acad2' AND load\(" > file_spacy_2_en_engagement_spl_RoBERTa_acad2_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_tei2go' AND load\(" > file_spacy_2_en_tei2go_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import de_tei2go' AND load\(" > file_spacy_2_de_tei2go_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import es_tei2go' AND load\(" > file_spacy_2_es_tei2go_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import fr_tei2go' AND load\(" > file_spacy_2_fr_tei2go_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import it_tei2go' AND load\(" > file_spacy_2_it_tei2go_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import pt_tei2go' AND load\(" > file_spacy_2_pt_tei2go_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pipeline' AND load\(" > file_spacy_2_en_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_nature_of_li_t_shirt' AND load\(" > file_spacy_2_en_nature_of_li_t_shirt_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import nameToStdName' AND load\(" > file_spacy_2_nameToStdName_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_pipeline' AND load\(" > file_spacy_2_en_pipeline_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import nl_middle_dutch_spacy' AND load\(" > file_spacy_2_nl_middle_dutch_spacy_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_nature_of_li_service' AND load\(" > file_spacy_2_en_nature_of_li_service_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_nature_of_li_shipping' AND load\(" > file_spacy_2_en_nature_of_li_shipping_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import en_nature_of_li_subscription' AND load\(" > file_spacy_2_en_nature_of_li_subscription_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import skills-experiences-ner' AND load\(" > file_spacy_2_skills-experiences-ner_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import uk_core_news_trf' AND load\(" > file_spacy_2_uk_core_news_trf_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import uk_core_news_sm' AND load\(" > file_spacy_2_uk_core_news_sm_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import uk_core_news_md' AND load\(" > file_spacy_2_uk_core_news_md_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import uk_core_news_lg' AND load\(" > file_spacy_2_uk_core_news_lg_load.csv
