src search "context:global select:file visibility:public count:all lang:Python content:'import spacy' AND load\(" > result_file_import_spacy_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import transformers' AND from_pretrained\(" > result_file_import_transformers_from_pretrained.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import transformers' AND pipeline\(" > result_file_import_transformers_pipeline.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import allennlp' AND from_path\(" > result_file_import_allennlp_from_path.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import asteroid' AND from_pretrained\(" > result_file_import_asteroid_from_pretrained.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import espnet2' AND from_pretrained\(" > result_file_import_espnet2_from_pretrained.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import nemo' AND from_pretrained\(" > result_file_import_nemo_from_pretrained.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import paddlenlp' AND from_pretrained\(" > result_file_import_paddlenlp_from_pretrained.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import pyannote' AND from_pretrained\(" > result_file_import_pyannote_from_pretrained.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import sentence_transformers' AND SentenceTransformer\(" > result_file_import_sentence_transformers_SentenceTransformer.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import speechbrain' AND from_hparams\(" > result_file_import_speechbrain_from_hparams.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import tensorflow_tts' AND from_pretrained\(" > result_file_import_tensorflow_tts_from_pretrained.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import timm' AND create_model\(" > result_file_import_timm_create_model.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import stanza' AND download\(" > result_file_import_stanza_download.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import stanza' AND Pipeline\(" > result_file_import_stanza_Pipeline.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import flair' AND load\(" > result_file_import_flair_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import fairseq' AND load_model_ensemble_and_task_from_hf_hub\(" > result_file_import_fairseq_load_model_ensemble_and_task_from_hf_hub.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import huggingface_hub' AND from_pretrained_keras\(" > result_file_import_huggingface_hub_from_pretrained_keras.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import huggingface_hub' AND from_pretrained_fastai\(" > result_file_import_huggingface_hub_from_pretrained_fastai.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import huggingface_hub' AND hf_hub_download\(" > result_file_import_huggingface_hub_hf_hub_download.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import bertopic' AND load\(" > result_file_import_bertopic_load.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import diffusers' AND from_pretrained\(" > result_file_import_diffusers_from_pretrained.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import open_clip' AND create_model_and_transforms\(" > result_file_import_open_clip_create_model_and_transforms.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import open_clip' AND get_tokenizer\(" > result_file_import_open_clip_get_tokenizer.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import peft' AND from_pretrained\(" > result_file_import_peft_from_pretrained.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import span_marker' AND from_pretrained\(" > result_file_import_span_marker_from_pretrained.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import huggingface_sb3' AND load_from_hub\(" > result_file_import_huggingface_sb3_load_from_hub.csv
src search "context:global select:file visibility:public count:all lang:Python content:'import pythae' AND load_from_hf_hub\(" > result_file_import_pythae_load_from_hf_hub.csv
